products = [
  {
    "id": "1",
    "name": "Cactus Plant",
    "image": "/images/cactus.jpg",
    "description": "Great cactus plant for your working table",
    "brand": "Home-Plant",
    "category": "Plant",
    "price": 30.29,
    "stock": 20,
    "rating": 4.9,
    "totalReview": 12,
  },
  {
    "id": "2",
    "name": "Art Plant",
    "image": "/images/art-plant.jpg",
    "description": "Plant for to improve your room design",
    "brand": "Home-Plant",
    "category": "Plant",
    "price": 25.4,
    "stock": 0,
    "rating": 4.2,
    "totalReview": 15,
  },
  {
    "id": "3",
    "name": "Bookcase",
    "image": "/images/book-shelf.jpg",
    "description": "Artistic book shelf mini",
    "brand": "Blizzard Decoration",
    "category": "Furniture",
    "price": 25.4,
    "stock": 10,
    "rating": 4.2,
    "totalReview": 15,
  },
  {
    "id": "4",
    "name": "Chair",
    "image": "/images/art-plant.jpg",
    "description": "Comfortable chair for working",
    "brand": "Blizzard Decoration",
    "category": "Furniture",
    "price": 99.4,
    "stock": 10,
    "rating": 4.7,
    "totalReview": 6,
  },
  {
    "id": "5",
    "name": "Coffee Table",
    "image": "/images/coffee-table.jpg",
    "description": "Coffee Table, really simplify your living room",
    "brand": "Blizzard Decoration",
    "category": "Furniture",
    "price": 75.0,
    "stock": 3,
    "rating": 3.6,
    "totalReview": 4,
  },
  {
    "id": "6",
    "name": "Drawer Set",
    "image": "/images/drawer-set.jpg",
    "description":
      "All in one drawer set, get this cool decoration into your home office",
    "brand": "Haime",
    "category": "Furniture",
    "price": 200.2,
    "stock": 10,
    "rating": 4.75,
    "totalReview": 150,
  },
  {
    "id": "7",
    "name": "Drawer ",
    "image": "/images/drawer.jpg",
    "description": "Drawer ",
    "brand": "Blizzard Decoration",
    "category": "Furniture",
    "stock": 10,
    "rating": 3.6,
    "totalReview": 12,
  },
  {
   "id": "8",
   "name": "Home Plant",
   "image": "/images/home-plant.jpg",
   "brand": "Home-Plant",
   "category": "Plant",
   "price": 25.4,
   "stock": 10,
   "rating": 4.2,
   "totalReview": 15,
  },
  {
    "id": "9",
    "name": "Artistic Journal",
    "image": "/images/journal.jpg",
    "description": "Journal d art",
    "brand": "Miho",
    "category": "Supplies",
    "price": 15.4,
    "stock": 100,
    "rating": 4.9,
    "totalReview": 120,
  },
  {
    "id": "10",
    "name": "Paper Organizer",
    "image": "/images/paper-organizer.jpg",
    "description": "Paper organizer , organize your paper work",
    "brand": "Miho",
    "category": "Supplies",
    "price": 5.4,
    "stock": 1000,
    "rating": 4.7,
    "totalReview": 150,
  },
  {
    "id": "11",
    "name": "Office Plant",
    "image": "/images/plant.jpg",
    "description": "Office plant, make your work day amazing",
    "brand": "Home-Plant",
    "category": "Plant",
    "price": 25.4,
    "stock": 10,
    "rating": 4.2,
    "totalReview": 15,
  },
  {
    "id": "12",
    "name": "Table Set",
    "image": "/images/table-set.jpg",
    "description": "Table set, for your dining",
    "brand": "Haime",
    "category": "Furniture",
    "price": 225.4,
    "stock": 10,
    "rating": 4.2,
    "totalReview": 1,
  },
  {
    "id": "13",
    "name": "Working Table set",
    "image": "/images/working-table-set.jpg",
    "description": "Working table set, complete in 1 go",
    "brand": "Furniture",
    "category": "Haime",
    "price": 365.0,
    "stock": 12,
    "rating": 4.8,
    "totalReview": 3,
  },
  {
    "id": "14",
   "name": "Simple Working Set",
   "image": "/images/working-table-set2.jpg",
   "description": "Table and Chair set",
   "brand": "Haime",
   "category": "Furniture",
   "price": 199.99,
  "stock": 10,
  "rating": 4.2,
  "totalReview": 5,
  },
]