export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST";
export const USER_LOGIN_SUCESS = "USER_LOGIN_SUCESS";
export const USER_LOGIN_FAIL = "USER_LOGIN_FAIL";
export const USER_LOG_OUT = "USER_LOG_OUT";

export const USER_REGISTER_REQUEST = "USER_REGISTER_REQUEST";
export const USER_REGISTER_SUCESS = "USER_REGISTER_SUCESS";
export const USER_REGISTER_FAIL = "USER_REGISTER_FAIL";

export const USER_PROFILE_REQUEST = "USER_PROFILE_REQUEST";
export const USER_PROFILE_SUCESS = "USER_PROFILE_SUCESS";
export const USER_PROFILE_FAIL = "USER_PROFILE_FAIL";

export const UPDATE_PROFILE_REQUEST = "USER_PROFILE_REQUEST";
export const UPDATE_PROFILE_SUCESS = "USER_PROFILE_SUCESS";
export const UPDATE_PROFILE_FAIL = "USER_PROFILE_FAIL";
