# Generated by Django 4.0.4 on 2022-07-13 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_shippingaddress_phonenumber'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='qty',
            new_name='quantity',
        ),
    ]
